# Generated by Django 4.2.2 on 2023-06-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='descricao',
            field=models.TextField(default='descrição'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='legenda',
            field=models.CharField(default='legenda22', max_length=150),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='nome',
            field=models.CharField(default='nome', max_length=100),
        ),
    ]
